build:
  violationcomments:
    image: fdplugins/android
    pull: true
    commands:
    - gradle :app:assembleAndroidTest
    - gradle :app:assembleDebug
    - gradle :app:lintDebug
    - gradle :app:checkstyle
    - gradle :app:findbugs
    - gradle :app:pmd
